// File generated by FlutterFire CLI.
// Run `dart run flutterfire_cli:flutterfire configure` (or `flutterfire configure`)
// to replace this with your project's Firebase options.
//
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for the app.
/// Replace this file by running: dart run flutterfire_cli:flutterfire configure
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApO1yyhI4sf4LZFkHb6B7y7Eoy8ehmMN4',
    appId: '1:1085160923066:android:8400274ba5d75302398783',
    messagingSenderId: '1085160923066',
    projectId: 'professorowl-b8694',
    storageBucket: 'professorowl-b8694.firebasestorage.app',
  );
}
